### ISSUE TITLE
Systematically use UTC for the date format

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#227]
This goes in the way of defining acceptable and meaningful conventions to homogenize our data.

**Comment by durack1** [comment]
@jservonnat I wonder where these issues are appearing - when I take a look at one of the json files we provide with the package (PR results from the CMIP5 piControl simulations):
ster/data/CMIP_metrics_results/CMIP5/piControl/pr_2.5x2.5_esmf_linear_metrics.json#L10,L32

It seems to me that some of the timestamps are obtained from the source files, which themselves would have to be in Z/UTC time otherwise we'd need to parse this with region information to map back to UTC.

Which attributes/values are required to be UTC: ```RefTrackingDate```, any others?

**Comment by jservonnat** [comment]
@durack1 it's more on my side, with SimTrackingDate and MetricTrackingDate (both used in the IPSL context).

**Comment by durack1** [comment]
@doutriaux1 this is a good idea, setting as a 1.1 milestone and assigning you..

**Comment by gleckler1** [comment]
@durack1 is this implemented?

**Comment by durack1** [comment]
@doutriaux1 following the query from @gleckler1 is this done yet?

**Comment by doutriaux1** [comment]
@durack1 I'm waiting for the year mark before looking at it :wink:

**Comment by doutriaux1** [comment]
and the second year mark to actually implement it :stuck_out_tongue_winking_eye:

**Comment by durack1** [comment]
@doutriaux1 it would seem to me that one year and four months should be a suitable "settling" time.. Should this be reset as a `1.1` milestone for the end of the week?

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 Great to get this working for Jerome in > v1.1 ... my only concern with now is that things are functioning properly... there were difficulties with the pytz library in durolib which I thought was being used to deal with the UTC thing but maybe I've garbled that.

**Comment by jservonnat** [comment]
Hi @durack1 @gleckler1 @doutriaux1! Let's say this is not a priority for me, I totally forgot it... Still, I think this would be a good thing anyway, but it doesn't come into play in the way I work.
So feel free to spend your time on something else and close this issue if you want ;).
