### ISSUE TITLE
Conflicts within the json file when running on multiple realizations

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#228]
The actual structure of the json file could induce conflicts with the name of the realization, in case of multiple realizations within the same json file. On one hand we have the "SimulationDescription" block that contains the realization (associated with a key 'SimName', which is convenient to read the json file). On the other hand we have the realization within the tree, below "SimulationDescription".
![capture d ecran 2015-01-23 a 18 32 57](https://cloud.githubusercontent.com/assets/7254214/5879263/e15be346-a32d-11e4-95b4-1f2b7fe8b418.png)
For the moment the driver does not make a loop on the realization, but in case it will in the future, there might be a conflict here to be considered.

**Comment by durack1** [comment]
@jservonnat @doutriaux1 I really do wonder if we should standardize "realization" as we keep referring to rather than "SimName" which is what we currently have in the outputs - it seems silly to have two different names when we keep describing these things within conversation (or issue reports as above) as "Realization"

**Comment by jservonnat** [comment]
@durack1 That's fine with me!
