### ISSUE TITLE
Bounds for regridding ocean data

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#247]
@doutriaux1 @gleckler1 @durack1
I'm having troubles with calculating metrics on my IPSL outputs (on the ORCA grid of the NEMO model) ; there is apparently a problem with the regridding that is asking for lon and lat bounds that are not present in my input netcdf file. The regridding tool is esmf, and the method is linear. If I try with the regrid2 tool, it automatically switches to esmf.
In spring last year, I remember having calculated metrics on tos (or zos) on an IPSL file. The lon and lat bounds were not in this file neither.
Do you know if there is possibility to avoid this problem of missing bounds in the input file? Apparently it won't be that easy to add them directly in the outputs... or at least, let's say that it would be a little bit of work.
Thanks!

**Comment by doutriaux1** [comment]
if your file is not CF compliant there's nothing we can do about it.

**Comment by durack1** [comment]
@jservonnat there was an issue with one of the IPSL grids with overlapping longitudes - there is no way that the software can automagically fix a file that's broken and is the reason @doutriaux1 closed this above..

It might be useful to provide this feedback through to Gurvan or others so that these grids are indeed checked against the CF standards - if you wanted to check the file in question to make sure that our assumptions are sound: http://puma.nerc.ac.uk/cgi-bin/cf-checker.pl
