### ISSUE TITLE
Implement Covey et al Diurnal cycle metrics

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#342]

**Comment by covey1** [comment]
One extension planned for the Metrics Package involves data at high time frequency, e.g. 3-hourly data instead of the usual monthly means. CMIP5 includes 23 two-dimensional atmospheric fields sampled every 3 hours. An increasing number of these fields are observed globally by satellites at high space/time resolution, e.g. TRMM precipitation data in the Obs4MIPs database. The attached files provide a starting point for analysis of both the observed and model-simulated diurnal cycle that such data imply.

**Comment by gleckler1** [comment]
@doutriaux1  @covey1 We finally have in-house xmls to work with to advance this:  /work/durack1/cmip5/historical/atm/3hr/pr

CD, CV Lets meet to discuss how to advance this as it is now a hi priority in our timeline as determined by SFA milestones

**Comment by durack1** [comment]
@gleckler1 out of curiosity, who is the "CV" guy..?

**Comment by gleckler1** [comment]
@doutriaux1 @covey1 Scratch that should read CC

**Comment by durack1** [comment]
@gleckler1 just edit the existing comment.. I just did.. And then deleted all the redundant ones..

**Comment by gleckler1** [comment]
@doutriaux1 @covey1  one thing that is going to be a challenge here is that we may find the xmls to be very slow... thats ok, as long as they work.

**Comment by covey1** [comment]
Peter and Paul,

I'm free to meet with you any time. I could apply the new XMLs to scripts
I put on GitHub a while ago--or first get those scripts in synch with my
new improved methods. Your choice.

C


-----Original Message-----
From: gleckler1 <notifications@github.com>
Reply-To: PCMDI/pcmdi_metrics
<reply+012b0bcdb0e5363417993dc56c89ecb20d543df9148a094b92cf0000000113d5e1a8
92a169ce09336cb2@reply.github.com>
Date: Wednesday, August 24, 2016 at 3:28 PM
To: PCMDI/pcmdi_metrics <pcmdi_metrics@noreply.github.com>
Cc: Curt Covey <covey1@llnl.gov>, Mention <mention@noreply.github.com>
Subject: Re: [PCMDI/pcmdi_metrics] Implement Covey et al Diurnal cycle
metrics (#342)

**Comment by gleckler1** [comment]
implemented!
