### ISSUE TITLE
setup.py and conda update

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#374]
Considering we've moved to a `conda` install path the `setup.py` and directory structure needs a re-think - will have to consult @doutriaux1 to figure out what is in and out of the current `conda` build

**Comment by gleckler1** [comment]
@durack1 @doutriaux1  I think the demo dir is getting picked up by conda without the setup.py (see below).   What is in v1.1 demo is abit mucked up because the model subdirectories were not git removed before the tag.   But otherwise I think its ok.   But I agree we need to discuss how/why the setup.py is used...

/export/gleckler1/anaconda2
[gleckler1@oceanonly ~/anaconda2]$ ls -lrt
total 164
-rw-r--r--   1 gleckler1 climate  4524 Feb  4 12:46 LICENSE.txt
drwxr-xr-x   2 gleckler1 climate  4096 May  9 10:24 envs
drwxr-xr-x   3 gleckler1 climate  4096 May  9 10:24 Examples
drwxr-xr-x   3 gleckler1 climate  4096 May  9 10:24 etc
drwxr-xr-x   3 gleckler1 climate  4096 May  9 10:24 ssl
drwxr-xr-x   4 gleckler1 climate  4096 May  9 10:24 imports
drwxr-xr-x   3 gleckler1 climate  4096 May  9 10:24 tests
drwxr-xr-x  13 gleckler1 climate  4096 May  9 10:24 plugins
drwxr-xr-x 111 gleckler1 climate  4096 May  9 10:24 mkspecs
drwxr-xr-x   3 gleckler1 climate  4096 May  9 15:26 man
drwxr-xr-x   3 gleckler1 climate  4096 May  9 15:27 mod
drwxr-xr-x   3 gleckler1 climate  4096 May 20 16:16 var
drwxr-xr-x  53 gleckler1 climate 12288 Jun 24 15:45 include
drwxr-xr-x  24 gleckler1 climate  4096 Jun 24 15:45 share
drwxr-xr-x  13 gleckler1 climate 36864 Jun 24 15:45 lib
drwxr-xr-x 229 gleckler1 climate 20480 Jun 24 15:45 pkgs
drwxr-xr-x   2 gleckler1 climate 16384 Jun 24 15:45 conda-meta
drwxr-xr-x   3 gleckler1 climate  4096 Jun 27 14:41 doc
drwxr-xr-x   3 gleckler1 climate 12288 Jun 30 11:34 bin
drwxr-xr-x   7 gleckler1 climate  4096 Jul  1 10:53 demo

**Comment by durack1** [comment]
So this is what you get when using conda `envs`:
```
(uvcdat)durack1@oceanonly:[~]:[942]> source activate pcmdi_metrics
discarding /export/durack1/anaconda2/envs/uvcdat/bin from PATH
prepending /export/durack1/anaconda2/envs/pcmdi_metrics/bin to PATH
(pcmdi_metrics)durack1@oceanonly:[~]:[943]> ls -al /export/durack1/anaconda2/envs/pcmdi_metrics/
total 68K
drwxr-xr-x 10 durack1 climate 4.0K Jul  6 14:27 .
drwxr-xr-x  6 durack1 climate 4.0K Jul  6 14:27 ..
drwxr-xr-x  3 durack1 climate 4.0K Jul  6 14:27 bin
drwxr-xr-x  2 durack1 climate 4.0K Jul  6 14:27 conda-meta
drwxr-xr-x  3 durack1 climate 4.0K Jul  6 14:27 doc
drwxr-xr-x 23 durack1 climate 4.0K Jul  6 14:27 include
drwxr-xr-x 12 durack1 climate  32K Jul  6 14:27 lib
drwxr-xr-x  3 durack1 climate 4.0K Jul  6 14:27 mod
drwxr-xr-x 18 durack1 climate 4.0K Jul  6 14:27 share
drwxr-xr-x  3 durack1 climate 4.0K Jul  6 14:27 ssl
(pcmdi_metrics)durack1@oceanonly:[~]:[943]>
```

There is no `src` dir or other things that `setup.py` is meant to create

**Comment by doutriaux1** [comment]
@gleckler1 just let me know what `demo` you want to be distributed I'll set the rest up.

**Comment by gleckler1** [comment]
closely related to #371

**Comment by durack1** [comment]
@gleckler1 if you see it as a duplicate copy across the relevant info and close the less relevant one..

**Comment by durack1** [comment]
@doutriaux1 @gleckler1 are we done with this?
