### ISSUE TITLE
MFW extremes

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#534]

**Comment by doutriaux1** [comment]
Michael F. Wehner? 😉

**Comment by durack1** [comment]
@mfwehner your name may have been raised here

**Comment by gleckler1** [comment]
Yes, I'll be putting MFW's code in here for us to chip away at.   We'll get him in the loop!

**Comment by gleckler1** [comment]
@mfwehner see updated code with print statements to track down error:
https://github.com/PCMDI/pcmdi_metrics/blob/534_pjg_mfw_extremes/src/python/devel/extremes/scripts/driver_extrema_longrun_pentad.py

Compare with execution below ... I suspect the slab.shape should be ~365 but its the entire timeseries...

(pmp_0808_py2.7) bash-4.1$ python -i driver_extrema_longrun_pentad.py 
starting annual y1 y2 and time.shape  61   205   (145,)
t1 and t2 beg end  53288.5   53289.5   53288.5   53289.5
b e tim[b] and tim[e]  0   -1   0.5   53289.5
time to read year and slab shape  61.3138439655   (53290, 90, 144)
before while ii<ndays

**Comment by mfwehner** [comment]
> On Sep 10, 2018, at 4:35 PM, gleckler1 <notifications@github.com> wrote:
> 
> Compare with execution below ... I suspect the slab.shape should be ~365 but its the entire timeseries...
> 
> 
Yes, let me take a look. But I have some python execution problems of my own at NERSC. I think a lib changed and I don’t believe anything…
m


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Michael Wehner
mfwehner@lbl.gov
https://crd.lbl.gov/departments/computational-science/ccmc/staff/staff-members/michael-wehner/


Senior Staff Scientist, Lawrence Berkeley National Laboratory

US DOE Policy 411.2A: When expressing opinions on policy matters to the public and media, research personnel must make it clear when they are expressing their personal views, rather than those of the Department, the U.S. Government, or their respective institutions. Public representation of Government or DOE positions or policies must be cleared through their program management to include DOE headquarters. In accordance with this policy, any material in this email should be considered the opinion of the sender and not necessarily that of the US Dept. of Energy, the University of California or the Lawrence Berkeley National Laboratory.
