### ISSUE TITLE
rename /pcmdi_metrics to /summary_statistics

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#729]
@lee1043 @acordonez   This simple change may take more work.   I expect setup.py will need to be modified.   Any other things come to mind before I get started?

**Comment by lee1043** [comment]
@gleckler1 I think changes should be made in `setup.py` mostly. No other things come to my mind neither.

**Comment by acordonez** [comment]
@gleckler1 @lee1043 All the package references in our scripts would need to be updated, e.g.
from pcmdi_metrics.monsoon_sperber.lib import sperber_metrics 
would need to be
from summary_statistics.monsoon_sperber.lib import sperber_metrics

**Comment by gleckler1** [comment]
@lee1043 @acordonez  and maybe in some codes like below? ...

https://github.com/PCMDI/pcmdi_metrics/blob/master/pcmdi_metrics/diurnal/scripts/compositeDiurnalStatistics.py#L26

**Comment by lee1043** [comment]
@acordonez that is a great and very critical point! Thanks for bring that in. In another code (ENSO metric) I have seen the most upper level could be given arbitrarily instead of directory name.

e.g.:
https://github.com/CLIVAR-PRP/ENSO_metrics/blob/903f12a416b21f56f745001ae9ed2ebbf65bc779/pmp_driver/PMPdriver_EnsoMetrics.py#L19

and 

https://github.com/CLIVAR-PRP/ENSO_metrics/blob/903f12a416b21f56f745001ae9ed2ebbf65bc779/setup.py#L61

I don't know if we can do something similar here. We may need some study on it.

**Comment by gleckler1** [comment]
@lee1043 @acordonez   I'll try it out on a branch and keep you posted.
