### ISSUE TITLE
Simplify & Modernize PMP’s Development/Release Workflow

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#776]
Work plan document is available [here](https://docs.google.com/document/d/1Amh3t2nDPheJKHCu4Dg-AqTuwry7OEHXXIp1XyCsHiI/edit?usp=sharing).

- [x] 1. Clean up unnecessary yaml files, centralize bash scripts and refactor, decouple from unnecessary external dependencies (e.g., Anaconda build tool from CDAT)
- [x] 2. Setup conda-forge feedstock repo
- [x] 3. Setup Github Action
  - [x] Builds development env
  - [ ] Runs revamped test suite 
  - [ ] Enable nightly and PR test on local (if easy enough) (using tool like pytest)
- [ ] 4. Add unit testing infrastructure (pytest and pytest-cov)
- [ ] 5. Revamp unit tests Dependent on 4

**Comment by lee1043** [comment]
https://github.com/PCMDI/pcmdi_metrics/issues/774 is related to above 1.

**Comment by lee1043** [comment]
https://github.com/PCMDI/pcmdi_metrics/issues/787 and https://github.com/PCMDI/pcmdi_metrics/issues/795 are related to above 2.

**Comment by lee1043** [comment]
I presume the current PMP conda release at https://anaconda.org/PCMDI/pcmdi_metrics will be replaced one from conda forge, is that true? In that case, what would be the usage of this conda release page? I think the current downloading count is retrieved from this page, not sure is there any way to continue use it or merge it to conda forge channel.  

@acordonez @tomvothecoder @jasonb5 any thoughts?

**Comment by acordonez** [comment]
@lee1043 yes, the conda-forge channel version of PMP will replace our current Anaconda channel. Not sure what the best thing to do with the old channel is - it might be confusing to have both online. 
How do we currently get statistics from Anaconda?

**Comment by lee1043** [comment]
The current download badge in the front [README](https://github.com/PCMDI/pcmdi_metrics/blob/main/README.md) file,  [![Anaconda-Server Badge](https://anaconda.org/pcmdi/pcmdi_metrics/badges/downloads.svg)](https://anaconda.org/pcmdi/pcmdi_metrics), is from anaconda as https://anaconda.org/pcmdi/pcmdi_metrics/badges/downloads.svg, so coming from the old anaconda channel. 

I agree having both channels would be confusing. Not sure neither for what to do with the old channel. @tomvothecoder @jasonb5 do you have any advice?

**Comment by tomvothecoder** [comment]
> @lee1043 yes, the conda-forge channel version of PMP will replace our current Anaconda channel. Not sure what the best thing to do with the old channel is - it might be confusing to have both online.

[`PCMDI/pcmdi_metrics`](https://anaconda.org/PCMDI/pcmdi_metrics) has to remain active to keep older versions of the package available for download. If you wanted to disable the `PCMDI` channel, the older versions would also need to be rereleased on `conda-forge`. However, that's probably a very difficult task that I don't recommend doing.

A similar scenario happened with `e3sm_diags`. It was originally hosted on `e3sm/e3sm_diags`, but newer versions are now hosted on `conda-forge/e3sm_diags`.

> How do we currently get statistics from Anaconda?

The download count is pulled from package hosted on the [PCMDI channel](https://anaconda.org/PCMDI/pcmdi_metrics/badges). If you want to keep this badge in addition to the `conda-forge` downloads count badge, you might need to figure out a way to change the text of the badge to say something like "downloads <= v.x.x.x".

---

Here are a few things I'd do:
- Update Anaconda channel references in the docs from `PCMDI` to `conda-forge` 
  - Maybe add a note in the README and docs that the `PCMDI` channel hosts versions <= x.x.x, while `conda-forge` hosts all versions after that
- Keep `PCMDI/pcmdi_metrics` up for all of the older versions since they won't be available on `conda-forge/pcmdi_metrics`
- Replace README badges with `conda-forge` badges (e.g., https://anaconda.org/conda-forge/xcdat/badges)

**Comment by acordonez** [comment]
@lee1043  It looks like we can also get badges for the conda-forge packages, e.g. for cmec-driver: https://anaconda.org/conda-forge/cmec_driver/badges. So it looks like we can replaces those paths in the README with the conda-forge ones (although we'd be starting from 0 again with the download count).
