### ISSUE TITLE
Add new metrics

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#87]
Following the 24th Sept 2014 email to GFDL the following improvements were listed:

Adding new metrics including:  monsoon precipitation index, total sea-ice extent, ILAMB land metrics (in collaboration with ORNL), upper ocean heat content, Koppen climate. Also of interest is the diurnal cycle of precip (based 3hr data, ref TRMM). And there are also the potential collaborations we've previously discussed (Shukla et al., Knutti et al). In any case, the intent of our package is that it will always include results from all available CMIP3/5/6 models.

**Comment by durack1** [comment]
As per #24 @jservonnat wanted to add another metric "latitude of the subtropical jets" - this additional metric has been merged into this issue

**Comment by jservonnat** [comment]
Questions about the best way to add custom metrics...
I've been experiencing the compute_custom_metrics parameter in the parameter file to add my diagnostic on the latitude of the jets. It works pretty well, and adds my metrics results to the results of the pcmdi metrics.
I've got a couple of questions however.
What happens if I want to point to different custom metrics?
For example, in the parameter file:
"
import pcmdi_metrics
compute_custom_metrics = pcmdi_metrics.ipsl.compute_metrics
"
As far as I understand, we can point to only one compute_metrics function.
A totally acceptable solution would be to have a set of parameter files ; each parameter file points to one custom compute_metrics function, with its associated variable and type of file, regridding, blablabla...
The problem is that the standard PCMDI metrics will be recalculated every time automatically (the way it is coded in the driver at the moment).
So a solution would be to precise from the parameter file if we want to compute both PCMDI metrics and custom metrics, or only one at a time. This would imply slight modifications in the driver.

All this because at IPSL we would like to develop a whole set of metrics for the different components. The Metrics Package seems perfectly suitable for this purpose, keeping in mind that we have to control as many things as possible from the parameter file (as you guys teached me). I'm aware of the fact the main purpose of the Metrics Package is to work on the CMIP archives, but the changes proposed here would have no conflict with this purpose and would broaden the use of the package (in my point of view).

Open to discussions!

**Comment by jservonnat** [comment]
Also as you know, I'm highly interested and concerned by the future metrics that will be added to the existing collection.
Could we consider creating an issue with the list of coming/wanted metrics, who is in charge of the development, and when should it be available?

**Comment by durack1** [comment]
@jservonnat you can indeed start appending a list and justification for why this would/is useful.. github provides a nice way of doing this:

Proposed new metrics:
- [ ] Add new metrics using the sftlf (land/ocean only)
- [ ] Jerome's favourite metrics
- [ ] Etc
